### ISSUE TITLE
Session ID's

### ISSUE THREAD

**Issue by Vrganj** [jellz/minehut-file-watcher#1]
Update this to work with session ID's.

**Comment by jellz** [comment]
Please elaborate

**Comment by jellz** [comment]
@Vrganj I'm closing this issue now due to lack of response. Feel free to reply to this issue if you have anything more to add and I'll reopen it.

**Comment by Vrganj** [comment]
The api uses the `x-session-id` header now, too. You can get it the same way you got the token.
